create extension if not exists pgcrypto;

do $$ begin
  if not exists(select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where n.nspname='public' and t.typname='exchange_kind') then create type public.exchange_kind as enum('reply','letter'); end if;
  if not exists(select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where n.nspname='public' and t.typname='exchange_visibility') then create type public.exchange_visibility as enum('public','private'); end if;
  if not exists(select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where n.nspname='public' and t.typname='uta_awase_vote') then create type public.uta_awase_vote as enum('left','right','draw'); end if;
end $$;
alter type public.exchange_kind add value if not exists 'reply';alter type public.exchange_kind add value if not exists 'letter';
alter type public.exchange_visibility add value if not exists 'public';alter type public.exchange_visibility add value if not exists 'private';
alter type public.uta_awase_vote add value if not exists 'left';alter type public.uta_awase_vote add value if not exists 'right';alter type public.uta_awase_vote add value if not exists 'draw';
begin;

create table if not exists public.users(id uuid primary key references auth.users(id) on delete cascade,user_number integer,created_at timestamptz not null default now());
alter table public.users add column if not exists user_number integer;
alter table public.users add column if not exists created_at timestamptz default now();
create table if not exists public.themes(id uuid primary key default gen_random_uuid(),date date,title text,seasonal_text text,created_at timestamptz default now());
alter table public.themes add column if not exists date date;
alter table public.themes add column if not exists title text;
alter table public.themes add column if not exists seasonal_text text;
alter table public.themes add column if not exists created_at timestamptz default now();
create table if not exists public.poems(id uuid primary key default gen_random_uuid(),user_id uuid references public.users(id) on delete cascade,theme_id uuid references public.themes(id) on delete cascade,line_1 text,line_2 text,line_3 text,line_4 text,line_5 text,selected_as_daily_pick boolean default false,created_at timestamptz default now());
alter table public.poems add column if not exists user_id uuid;
alter table public.poems add column if not exists theme_id uuid;
alter table public.poems add column if not exists line_1 text;
alter table public.poems add column if not exists line_2 text;
alter table public.poems add column if not exists line_3 text;
alter table public.poems add column if not exists line_4 text;
alter table public.poems add column if not exists line_5 text;
alter table public.poems add column if not exists selected_as_daily_pick boolean default false;
alter table public.poems add column if not exists created_at timestamptz default now();

create table if not exists public.pinned_poems(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.users(id) on delete cascade,poem_id uuid not null references public.poems(id) on delete cascade,display_order smallint not null,created_at timestamptz default now());
create table if not exists public.user_glimpses(viewer_user_id uuid not null references public.users(id) on delete cascade,viewed_user_id uuid not null references public.users(id) on delete cascade,first_viewed_at timestamptz default now(),primary key(viewer_user_id,viewed_user_id));
create table if not exists public.poem_exchanges(id uuid primary key default gen_random_uuid(),initiator_user_id uuid not null references public.users(id),recipient_user_id uuid not null references public.users(id),root_poem_id uuid references public.poems(id),exchange_type public.exchange_kind not null,visibility public.exchange_visibility not null,last_sender_user_id uuid not null references public.users(id),created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.exchange_poems(id uuid primary key default gen_random_uuid(),exchange_id uuid not null references public.poem_exchanges(id) on delete cascade,sender_user_id uuid not null references public.users(id),line_1 text not null,line_2 text not null,line_3 text not null,line_4 text not null,line_5 text not null,created_at timestamptz default now());
create table if not exists public.reactions(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.users(id) on delete cascade,poem_id uuid not null references public.poems(id) on delete cascade,reaction_type text not null default 'aware',created_at timestamptz default now());
create table if not exists public.uta_awase_matches(id uuid primary key default gen_random_uuid(),theme_id uuid not null references public.themes(id),left_poem_id uuid not null references public.poems(id),right_poem_id uuid not null references public.poems(id),battle_date date not null,created_at timestamptz default now());
create table if not exists public.uta_awase_votes(id uuid primary key default gen_random_uuid(),match_id uuid not null references public.uta_awase_matches(id) on delete cascade,user_id uuid not null references public.users(id) on delete cascade,vote public.uta_awase_vote not null,created_at timestamptz default now());
create table if not exists public.uta_awase_results(id uuid primary key default gen_random_uuid(),theme_id uuid not null references public.themes(id),poem_id uuid not null references public.poems(id),score numeric not null,match_count integer not null,win_count integer not null,draw_count integer not null,loss_count integer not null,rank smallint,calculated_at timestamptz default now());
create table if not exists public.result_views(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.users(id) on delete cascade,theme_id uuid not null references public.themes(id) on delete cascade,viewed_at timestamptz default now());

alter table public.pinned_poems add column if not exists user_id uuid;alter table public.pinned_poems add column if not exists poem_id uuid;alter table public.pinned_poems add column if not exists display_order smallint;alter table public.pinned_poems add column if not exists created_at timestamptz default now();
alter table public.user_glimpses add column if not exists viewer_user_id uuid;alter table public.user_glimpses add column if not exists viewed_user_id uuid;alter table public.user_glimpses add column if not exists first_viewed_at timestamptz default now();
alter table public.poem_exchanges add column if not exists initiator_user_id uuid;alter table public.poem_exchanges add column if not exists recipient_user_id uuid;alter table public.poem_exchanges add column if not exists root_poem_id uuid;alter table public.poem_exchanges add column if not exists exchange_type public.exchange_kind;alter table public.poem_exchanges add column if not exists visibility public.exchange_visibility;alter table public.poem_exchanges add column if not exists last_sender_user_id uuid;alter table public.poem_exchanges add column if not exists created_at timestamptz default now();alter table public.poem_exchanges add column if not exists updated_at timestamptz default now();
alter table public.exchange_poems add column if not exists exchange_id uuid;alter table public.exchange_poems add column if not exists sender_user_id uuid;alter table public.exchange_poems add column if not exists line_1 text;alter table public.exchange_poems add column if not exists line_2 text;alter table public.exchange_poems add column if not exists line_3 text;alter table public.exchange_poems add column if not exists line_4 text;alter table public.exchange_poems add column if not exists line_5 text;alter table public.exchange_poems add column if not exists created_at timestamptz default now();
alter table public.reactions add column if not exists user_id uuid;alter table public.reactions add column if not exists poem_id uuid;alter table public.reactions add column if not exists reaction_type text default 'aware';alter table public.reactions add column if not exists created_at timestamptz default now();
alter table public.uta_awase_matches add column if not exists theme_id uuid;alter table public.uta_awase_matches add column if not exists left_poem_id uuid;alter table public.uta_awase_matches add column if not exists right_poem_id uuid;alter table public.uta_awase_matches add column if not exists battle_date date;alter table public.uta_awase_matches add column if not exists created_at timestamptz default now();
alter table public.uta_awase_votes add column if not exists match_id uuid;alter table public.uta_awase_votes add column if not exists user_id uuid;alter table public.uta_awase_votes add column if not exists vote public.uta_awase_vote;alter table public.uta_awase_votes add column if not exists created_at timestamptz default now();
alter table public.uta_awase_results add column if not exists theme_id uuid;alter table public.uta_awase_results add column if not exists poem_id uuid;alter table public.uta_awase_results add column if not exists score numeric;alter table public.uta_awase_results add column if not exists match_count integer;alter table public.uta_awase_results add column if not exists win_count integer;alter table public.uta_awase_results add column if not exists draw_count integer;alter table public.uta_awase_results add column if not exists loss_count integer;alter table public.uta_awase_results add column if not exists rank smallint;alter table public.uta_awase_results add column if not exists calculated_at timestamptz default now();
alter table public.result_views add column if not exists user_id uuid;alter table public.result_views add column if not exists theme_id uuid;alter table public.result_views add column if not exists viewed_at timestamptz default now();

do $$ begin
  if not exists(select 1 from pg_constraint where conname='users_number_range' and conrelid='public.users'::regclass) then alter table public.users add constraint users_number_range check(user_number between 0 and 9999) not valid; end if;
  if not exists(select 1 from pg_constraint where conname='pinned_poems_order_range' and conrelid='public.pinned_poems'::regclass) then alter table public.pinned_poems add constraint pinned_poems_order_range check(display_order between 1 and 3) not valid; end if;
  if not exists(select 1 from pg_constraint where conname='poem_exchanges_distinct_users' and conrelid='public.poem_exchanges'::regclass) then alter table public.poem_exchanges add constraint poem_exchanges_distinct_users check(initiator_user_id<>recipient_user_id) not valid; end if;
  if not exists(select 1 from pg_constraint where conname='poem_exchanges_kind_root' and conrelid='public.poem_exchanges'::regclass) then alter table public.poem_exchanges add constraint poem_exchanges_kind_root check((exchange_type='reply' and root_poem_id is not null) or (exchange_type='letter' and root_poem_id is null)) not valid; end if;
  if not exists(select 1 from pg_constraint where conname='reactions_aware_only' and conrelid='public.reactions'::regclass) then alter table public.reactions add constraint reactions_aware_only check(reaction_type='aware') not valid; end if;
end $$;

do $$ begin
  if not exists(select 1 from public.users where user_number is not null group by user_number having count(*)>1) then create unique index if not exists users_user_number_unique on public.users(user_number); else raise notice 'users.user_number has duplicates; unique index skipped'; end if;
  if not exists(select 1 from public.poems group by user_id,theme_id having count(*)>1) then create unique index if not exists poems_one_per_theme_unique on public.poems(user_id,theme_id); else raise notice 'duplicate daily poems exist; unique index skipped'; end if;
  if not exists(select 1 from public.pinned_poems group by user_id,poem_id having count(*)>1) then create unique index if not exists pinned_poems_user_poem_unique on public.pinned_poems(user_id,poem_id); else raise notice 'duplicate pinned poems exist; unique index skipped'; end if;
  if not exists(select 1 from public.pinned_poems group by user_id,display_order having count(*)>1) then create unique index if not exists pinned_poems_user_order_unique on public.pinned_poems(user_id,display_order); else raise notice 'duplicate pin order exists; unique index skipped'; end if;
  if not exists(select 1 from public.reactions group by user_id,poem_id,reaction_type having count(*)>1) then create unique index if not exists reactions_once_unique on public.reactions(user_id,poem_id,reaction_type); else raise notice 'duplicate reactions exist; unique index skipped'; end if;
  if not exists(select 1 from public.uta_awase_votes group by match_id,user_id having count(*)>1) then create unique index if not exists uta_awase_votes_once_unique on public.uta_awase_votes(match_id,user_id); else raise notice 'duplicate votes exist; unique index skipped'; end if;
  if not exists(select 1 from public.result_views group by user_id,theme_id having count(*)>1) then create unique index if not exists result_views_once_unique on public.result_views(user_id,theme_id); else raise notice 'duplicate result views exist; unique index skipped'; end if;
end $$;

create or replace function public.assign_user_number() returns trigger language plpgsql security definer set search_path=public as $$
declare chosen integer; begin perform pg_advisory_xact_lock(4389999); if new.user_number=0 and coalesce(auth.jwt()->>'role','')<>'service_role' then raise exception 'user number 0 is reserved'; end if; if new.user_number is null then select n into chosen from generate_series(1,9999)n where not exists(select 1 from public.users u where u.user_number=n) order by random() limit 1; if chosen is null then raise exception 'no user number remains'; end if; new.user_number:=chosen; end if; return new; end $$;
drop trigger if exists users_assign_number on public.users;
create trigger users_assign_number before insert on public.users for each row execute function public.assign_user_number();

create or replace function public.handle_new_auth_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.users(id) values(new.id) on conflict(id) do nothing; return new; end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_auth_user();
insert into public.users(id) select id from auth.users on conflict(id) do nothing;
do $$ declare r record; chosen integer; begin for r in select id from public.users where user_number is null loop select n into chosen from generate_series(1,9999)n where not exists(select 1 from public.users u where u.user_number=n) order by random() limit 1; update public.users set user_number=chosen where id=r.id; end loop; end $$;

create or replace function public.has_submitted_to_theme(p_theme_id uuid) returns boolean language sql security definer stable set search_path=public as $$ select exists(select 1 from public.poems where theme_id=p_theme_id and user_id=auth.uid()) $$;
create or replace function public.begin_exchange(p_recipient uuid,p_root_poem uuid,p_kind public.exchange_kind,p_visibility public.exchange_visibility,p_lines text[]) returns public.poem_exchanges language plpgsql security definer set search_path=public as $$
declare ex public.poem_exchanges;uid uuid:=auth.uid();begin if uid is null or uid=p_recipient then raise exception 'invalid recipient';end if;if array_length(p_lines,1)<>5 then raise exception 'a poem must have five lines';end if;if (p_kind='reply' and p_root_poem is null)or(p_kind='letter' and p_root_poem is not null)then raise exception 'invalid root poem';end if;if p_kind='reply' and not exists(select 1 from public.poems where id=p_root_poem and user_id=p_recipient)then raise exception 'recipient must own root poem';end if;if p_kind='letter' and not exists(select 1 from public.user_glimpses where viewer_user_id=uid and viewed_user_id=p_recipient)then raise exception 'recipient must first be glimpsed';end if;insert into public.poem_exchanges(initiator_user_id,recipient_user_id,root_poem_id,exchange_type,visibility,last_sender_user_id)values(uid,p_recipient,p_root_poem,p_kind,p_visibility,uid)returning * into ex;insert into public.exchange_poems(exchange_id,sender_user_id,line_1,line_2,line_3,line_4,line_5)values(ex.id,uid,p_lines[1],p_lines[2],p_lines[3],p_lines[4],p_lines[5]);return ex;end $$;
create or replace function public.add_exchange_poem(p_exchange_id uuid,p_lines text[]) returns public.exchange_poems language plpgsql security definer set search_path=public as $$
declare ex public.poem_exchanges;result public.exchange_poems;uid uuid:=auth.uid();begin select * into ex from public.poem_exchanges where id=p_exchange_id for update;if uid is null or uid not in(ex.initiator_user_id,ex.recipient_user_id)then raise exception 'not a participant';end if;if ex.last_sender_user_id=uid then raise exception 'await the other person';end if;if array_length(p_lines,1)<>5 then raise exception 'a poem must have five lines';end if;insert into public.exchange_poems(exchange_id,sender_user_id,line_1,line_2,line_3,line_4,line_5)values(p_exchange_id,uid,p_lines[1],p_lines[2],p_lines[3],p_lines[4],p_lines[5])returning * into result;update public.poem_exchanges set last_sender_user_id=uid,updated_at=now()where id=p_exchange_id;return result;end $$;
create or replace function public.my_poem_aware_count(p_poem_id uuid) returns bigint language sql security definer stable set search_path=public as $$ select count(*) from public.reactions r join public.poems p on p.id=r.poem_id where r.poem_id=p_poem_id and p.user_id=auth.uid()and r.reaction_type='aware' $$;
create or replace function public.replace_pinned_poems(p_poem_ids uuid[]) returns void language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid();poem_id uuid;position smallint:=1;begin if uid is null or coalesce(array_length(p_poem_ids,1),0)>3 then raise exception 'at most three poems';end if;if exists(select 1 from unnest(p_poem_ids)x left join public.poems p on p.id=x where p.id is null or p.user_id<>uid)then raise exception 'only own poems can be pinned';end if;delete from public.pinned_poems where user_id=uid;foreach poem_id in array p_poem_ids loop insert into public.pinned_poems(user_id,poem_id,display_order)values(uid,poem_id,position);position:=position+1;end loop;end $$;

create or replace view public.peek_poems with(security_invoker=true)as select pp.user_id,pp.display_order,p.id poem_id,p.line_1,p.line_2,p.line_3,p.line_4,p.line_5 from public.pinned_poems pp join public.poems p on p.id=pp.poem_id order by pp.user_id,pp.display_order;

alter table public.users enable row level security;alter table public.themes enable row level security;alter table public.poems enable row level security;alter table public.pinned_poems enable row level security;alter table public.user_glimpses enable row level security;alter table public.poem_exchanges enable row level security;alter table public.exchange_poems enable row level security;alter table public.reactions enable row level security;alter table public.uta_awase_matches enable row level security;alter table public.uta_awase_votes enable row level security;alter table public.uta_awase_results enable row level security;alter table public.result_views enable row level security;

drop policy if exists "numbers are readable" on public.users;create policy "numbers are readable" on public.users for select to authenticated using(true);
drop policy if exists "own user row" on public.users;create policy "own user row" on public.users for update to authenticated using(id=auth.uid())with check(id=auth.uid());
drop policy if exists "themes are readable" on public.themes;create policy "themes are readable" on public.themes for select to authenticated using(true);
drop policy if exists "own poems insert" on public.poems;create policy "own poems insert" on public.poems for insert to authenticated with check(user_id=auth.uid());
drop policy if exists "own poems readable" on public.poems;create policy "own poems readable" on public.poems for select to authenticated using(user_id=auth.uid());
drop policy if exists "past poems or unlocked gathering readable" on public.poems;create policy "past poems or unlocked gathering readable" on public.poems for select to authenticated using(exists(select 1 from public.themes t where t.id=theme_id and(t.date<current_date or public.has_submitted_to_theme(t.id))));
drop policy if exists "owner manages pinned poems" on public.pinned_poems;create policy "owner manages pinned poems" on public.pinned_poems for all using(user_id=auth.uid())with check(user_id=auth.uid());
drop policy if exists "authenticated sees pinned selection" on public.pinned_poems;create policy "authenticated sees pinned selection" on public.pinned_poems for select to authenticated using(true);
drop policy if exists "viewer records and sees own glimpses" on public.user_glimpses;create policy "viewer records and sees own glimpses" on public.user_glimpses for all using(viewer_user_id=auth.uid())with check(viewer_user_id=auth.uid());
drop policy if exists "participants see private; all see public" on public.poem_exchanges;create policy "participants see private; all see public" on public.poem_exchanges for select to authenticated using(visibility='public'or auth.uid()in(initiator_user_id,recipient_user_id));
drop policy if exists "exchange poems follow exchange visibility" on public.exchange_poems;create policy "exchange poems follow exchange visibility" on public.exchange_poems for select to authenticated using(exists(select 1 from public.poem_exchanges e where e.id=exchange_id and(e.visibility='public'or auth.uid()in(e.initiator_user_id,e.recipient_user_id))));
drop policy if exists "own aware rows only" on public.reactions;create policy "own aware rows only" on public.reactions for select using(user_id=auth.uid());
drop policy if exists "aware another poem" on public.reactions;create policy "aware another poem" on public.reactions for insert with check(user_id=auth.uid()and not exists(select 1 from public.poems p where p.id=poem_id and p.user_id=auth.uid()));
drop policy if exists "remove own aware" on public.reactions;create policy "remove own aware" on public.reactions for delete using(user_id=auth.uid());
drop policy if exists "matches readable while active" on public.uta_awase_matches;create policy "matches readable while active" on public.uta_awase_matches for select to authenticated using(battle_date<=current_date);
drop policy if exists "own votes readable" on public.uta_awase_votes;create policy "own votes readable" on public.uta_awase_votes for select using(user_id=auth.uid());
drop policy if exists "vote once and not own match" on public.uta_awase_votes;create policy "vote once and not own match" on public.uta_awase_votes for insert with check(user_id=auth.uid()and not exists(select 1 from public.uta_awase_matches m join public.poems l on l.id=m.left_poem_id join public.poems r on r.id=m.right_poem_id where m.id=match_id and auth.uid()in(l.user_id,r.user_id)));
drop policy if exists "published results readable" on public.uta_awase_results;create policy "published results readable" on public.uta_awase_results for select to authenticated using(calculated_at<=now());
drop policy if exists "own result views" on public.result_views;create policy "own result views" on public.result_views for all using(user_id=auth.uid())with check(user_id=auth.uid());

revoke insert,update,delete on public.exchange_poems from authenticated;revoke insert,update,delete on public.poem_exchanges from authenticated;
revoke all on function public.begin_exchange(uuid,uuid,public.exchange_kind,public.exchange_visibility,text[])from public;revoke all on function public.add_exchange_poem(uuid,text[])from public;revoke all on function public.my_poem_aware_count(uuid)from public;revoke all on function public.replace_pinned_poems(uuid[])from public;
grant execute on function public.begin_exchange(uuid,uuid,public.exchange_kind,public.exchange_visibility,text[])to authenticated;grant execute on function public.add_exchange_poem(uuid,text[])to authenticated;grant execute on function public.my_poem_aware_count(uuid)to authenticated;grant execute on function public.replace_pinned_poems(uuid[])to authenticated;

insert into public.themes(date,title,seasonal_text)select current_date,'言えなかったこと','白露' where not exists(select 1 from public.themes where date=current_date);
commit;
